import { Router } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import tasksRouter from "./tasks";
import pricingRouter from "./pricing";
import statsRouter from "./stats";
import sessionsRouter from "./sessions";
import adminRouter from "./admin";
import referralRouter from "./referral";
import promoRouter from "./promo";
import ticketsRouter from "./tickets";
import summariesRouter from "./summaries";
import courseworkRouter from "./coursework";
import illustrationsRouter from "./illustrations";
import paymentsRouter from "./payments";
import storageRouter from "./storage";
import uniquenessRouter from "./uniqueness";
import supportRouter from "./support";
import refundRouter from "./refund";
import quizRouter from "./quiz";
import { aiHeavyLimiter, aiNormalLimiter, authLimiter } from "../middlewares/rateLimit";

const router = Router();

router.use(healthRouter);
router.use("/auth", authLimiter, authRouter);
router.use("/users", usersRouter);
router.use("/tasks", aiHeavyLimiter, tasksRouter);
router.use("/pricing", pricingRouter);
router.use("/stats", statsRouter);
router.use("/sessions", aiNormalLimiter, sessionsRouter);
router.use("/admin", adminRouter);
router.use("/referral", referralRouter);
router.use("/promo", promoRouter);
import publicRouter from "./public";
router.use("/public", publicRouter);
router.use("/tickets", aiHeavyLimiter, ticketsRouter);
router.use("/summaries", aiHeavyLimiter, summariesRouter);
router.use("/coursework", aiHeavyLimiter, courseworkRouter);
router.use("/illustrations", aiHeavyLimiter, illustrationsRouter);
router.use("/payments", paymentsRouter);
router.use("/uniqueness", aiHeavyLimiter, uniquenessRouter);
router.use("/support", aiNormalLimiter, supportRouter);
router.use("/refund-requests", refundRouter);
router.use("/quiz", aiHeavyLimiter, quizRouter);
router.use(storageRouter);

export default router;
